### ISSUE TITLE
feat: add social meta tags for sharing purpose

### ISSUE THREAD

**Issue by peterpeterparker** [sansan88/miitmi#4]
### Feature Request

Meta tags are currently not specified in `index.html`. Before going live and before sharing the application, I think it would be good to add these, otherwise no social cards is going to be displayed when the url is going to be added to Twitter or Facebook or other social platforms.

See our [index.html](https://github.com/deckgo/deckdeckgo/blob/596adaf31e42801f9447d86c6e4a2a7c62c6b4ab/studio/src/index.html#L21) and meta tags description, author, canonical, og: and twitter: for example

**Comment by sansan88** [comment]
Thank you! great template :)
